AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  NotebookApiFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: ../
      Handler: backend/app.lambda_handler
      Runtime: python3.11
      Timeout: 10

      Policies:
        - DynamoDBCrudPolicy:
            TableName: notebook

      Environment:
        Variables:
          TABLE_NAME: notebook

      Events:

        GetNotes:
          Type: Api
          Properties:
            Path: /notes
            Method: get

        PostNotes:
          Type: Api
          Properties:
            Path: /notes
            Method: post

        PutNotes:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: put

        DeleteNotes:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: delete


  NotesTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: notebook
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: noteId
          AttributeType: S

      KeySchema:
        - AttributeName: noteId
          KeyType: HASH
