Resources:
  NotebookGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: backend/handlers/notebook_get.notepad_get
      Runtime: python3.11
      
      Events:
        NotebookGetApi:
          Type: Api
          Properties:
            Path: /notes
            Method: get

  
  NotebookWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: backend/handlers/notebook_post.notepad_post
      Runtime: python3.11
      
      Policies:
        - DynamoDBCrudPolicy:
            TableName: posted_notepad
      Environment:
        Variables:
          TABLE_NAME: posted_notepad
      
      Events:
        NotebookWriteApi:
          Type: Api
          Properties:
            Path: /notes
            Method: post

  NotesTables:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: posted_notepad
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: note_id
          AttributeType: S

      KeySchema:
        - AttributeName: note_id
          KeyType: HASH

